---
baseURL: /
canonifyURLs: true
defaultContentLanguage: ru
enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true
enableRobotsTXT: true
title: TulpaWiki
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true
      strikethrough: true
      table: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    tableOfContents:
      startLevel: 2
      endLevel: 3
      ordered: true
minify:
  minifyOutput: true
  tdewolff:
    css:
      keepCSS2: false
    html:
      keepConditionalComments: false
taxonomies:
  source: sources
  author: authors
module:
  imports:
    - path: gitlab.com/toby3d/hugo/webmonetization
mediaTypes:
  application/feed+json:
    delimiter: "."
    mainType: application
    subType: feed
    suffixes:
      - json
outputFormats:
  JSONFeed:
    name: JSONFeed
    mediaType: "application/feed+json"
    baseName: feed
    isPlainText: true
    rel: alternate
outputs:
  home:
    - HTML
    - JSON
  section:
    - HTML
    - JSONFeed
  page:
    - HTML
permalinks:
  blog: /blog/:year/:month/:filename
